version: '3.4'

services:
   nginx:
     image: olevezinho/loadbalancer
     environment:
      - SA_PASSWORD="DockerSql2017!""
      - ACCEPT_EULA="Y"
     build:
       context: ../nginx
     depends_on:
       - app
       - app2
     ports:
       - 80:80

   app:
     working_dir: /app
     image: olevezinho/mycalculatorwebapp:1.0.0.1
     environment:
      - ASPNETCORE_ENVIRONMENT=test
     build:
       context: .
     ports:
       - 8123:80

   app2:
     working_dir: /app
     image: olevezinho/mycalculatorwebapp:1.0.0.1
     environment:
      - ASPNETCORE_ENVIRONMENT=prod
     build:
       context: .
     ports:
       - 8124:80

#   app3:
#     working_dir: /app
#     image: olevezinho/mycalculatorwebapp:1.0.0.1
#     build:
#       context: .
#     ports:
#       - 8125:80
#
#   app4:
#     working_dir: /app
#     image: olevezinho/mycalculatorwebapp:1.0.0.1
#     build:
#       context: .
#     ports:
#       - 8126:80
